id: 83e11644-f5dd-286b-af2d-e4d20d9e678a
type: application
interactions:
  - targetId: f6f7a7a6-2bf2-48b4-9741-e3cbecb92b5d
    type: service
    level: component
  - targetId: a6fb0860-3993-e3bd-1be3-f9848937d59c
    type: domain
    level: component
annotations:
  - namespace: c4modeler
    name: position
    value:
      a9a5ef87-b2cb-84db-3366-56d339eee631:
        x: 140
        y: 124.5
name: NewApplication
description: Description for NewApplication
author: Code
baseApiUrl: ca/baseapi
